version: 0.0
os: linux
files:
  - source: /
    destination: /home/webapp/Lantern/lantern/lantern/lantern
permissions:
  - object: /home/webapp/Lantern/lantern/lantern/lantern/lantern
    owner: webapp
    group: webapp
hooks:
  AfterInstall:
    - location: /home/webapp/Lantern/lantern/lantern/scripts/after_install.sh
      timeout: 60
      runas: webapp