version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
      - image: circleci/mysql:5.7
        environment:
          MYSQL_DATABASE: lantern
          MYSQL_USER: lantern_user
          MYSQL_PASSWORD: lantern_pass
    environment:
      APP_ENV: testing
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: lantern
      DB_USERNAME: lantern_user
      DB_PASSWORD: lantern_pass
    steps:
      - checkout
      - run: sudo composer self-update --1
      - restore_cache:
          key: composer-v1-{{ checksum "lantern/composer.lock" }}
      - run:
          name: Install PHP libraries
          command: composer install -n --prefer-dist --working-dir=./lantern
      - save_cache:
          key: composer-v1-{{ checksum "lantern/composer.lock" }}
          paths:
            - vendor
      - restore_cache: 
          key: npm-v1-{{ checksum "lantern/package-lock.json" }}
      - run:
          name: npm ci
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi 
          working_directory: ./lantern
      - save_cache: 
          key: npm-v1-{{ checksum "lantern/package-lock.json" }}
          paths: 
            - node_modules
      - run:
          command: npm run dev
          working_directory: ./lantern
      - run:
          name: get ready for mysql
          command: |
            sudo apt-get update
            sudo apt-get install libpq-dev
            sudo docker-php-ext-install pdo_mysql
            dockerize -wait tcp://localhost:3306 -timeout 1m
      - run: 
          name: 
          command: php artisan migrate --env=testing
          working_directory: ./lantern --configuration=./lantern/phpunit.xml
      - run: 
          command: php artisan db:seed
          working_directory: ./lantern
      -run:
          name: PHP test
          command: vendor/phpunit/phpunit/phpunit tests/
          working_directory: ./lantern
