version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      - checkout
      - run: sudo composer self-update --1
      - restore_cache:
          key: composer-v1-{{ checksum "lantern/composer.lock" }}
      - run:
          name: Install PHP libraries
          command: composer install -n --prefer-dist --working-dir=./lantern
      - save_cache:
          key: composer-v1-{{ checksum "lantern/composer.lock" }}
          paths:
            - vendor
      - restore_cache: 
          key: npm-v1-{{ checksum "lantern/package-lock.json" }}
      - run:
          name: npm ci
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi 
          working_directory: ./lantern
      - save_cache: 
          key: npm-v1-{{ checksum "lantern/package-lock.json" }}
          paths: 
            - node_modules
      - run:
          command: npm run dev
          working_directory: ./lantern
